name: GitLab CI
on:
  push:
    branches-ignore:
    - documentation
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - name: Always
      run: echo 'Hello!'
