name: GitLab CI
on:
  push:
    branches-ignore:
    - documentation
  pull_request:
    branches-ignore:
    - documentation

defaults:
  run:
    shell: bash

jobs:
  #
  # Deferred GitLab pipelines on Levante at DKRZ:
  #
  levante-init:
    # if: github.repository == 'earth-system-radiation/rte-rrtmgp'
    runs-on: ubuntu-latest
    outputs:
      ref-name: ${{ steps.g-push-rev.outputs.ref-name }}
      pipeline-id: ${{ steps.gl-create-pipeline.outputs.pipeline-id }}
    steps:
    #
    # Check out GitHub repository
    #
    - name: Check out GitHub repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    #
    # Push to GitLab repository
    #
    - name: Push to GitLab repository
      id: g-push-rev
      uses: "skosukhin/git-ci-hub-lab/g-push-rev@v1"
      with:
        remote-url: ${{ vars.DKRZ_GITLAB_SERVER }}/${{ vars.DKRZ_GITLAB_PROJECT }}.git
        password: ${{ secrets.DKRZ_GITLAB_TOKEN }}
        ref-type: tag
        ref-message: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        force-push: true
    #
    # Create GitLab CI/CD Pipeline
    #
    - name: Create GitLab CI/CD Pipeline
      id: gl-create-pipeline
      uses: "skosukhin/git-ci-hub-lab/gl-create-pipeline@v1"
      with:
        server-url: ${{ vars.DKRZ_GITLAB_SERVER }}
        project-name: ${{ vars.DKRZ_GITLAB_PROJECT }}
        token: ${{ secrets.DKRZ_GITLAB_TOKEN }}
        ref-name: ${{ steps.g-push-rev.outputs.ref-name }}
        expected-sha: ${{ github.sha }}
  levante:
    runs-on: ubuntu-latest
    needs: levante-init
    strategy:
      fail-fast: false
      matrix:
        config-name: [nvhpc-gpu-openacc-DP, nvhpc-gpu-openacc-SP]
    steps:
    #
    # Build libraries, examples and tests (fetch the log)
    # Run examples and tests (fetch the log)
    # Compare the results (fetch the log)
    #
    - name: Build, run and check (fetch the log)
      uses: "skosukhin/git-ci-hub-lab/gl-attach-job@v1"
      with:
        server-url: ${{ vars.DKRZ_GITLAB_SERVER }}
        project-name: ${{ vars.DKRZ_GITLAB_PROJECT }}
        token: ${{ secrets.DKRZ_GITLAB_TOKEN }}
        pipeline-id: ${{ needs.levante-init.outputs.pipeline-id }}
        job-name: ${{ matrix.config-name }}
  levante-cleanup:
    runs-on: ubuntu-latest
    needs: [levante-init, levante]
    if: always() && needs.levante-init.result != 'skipped'
    continue-on-error: true
    steps:
    - uses: "skosukhin/git-ci-hub-lab/gl-delete-ref@v1"
      with:
        server-url: ${{ vars.DKRZ_GITLAB_SERVER }}
        project-name: ${{ vars.DKRZ_GITLAB_PROJECT }}
        token: ${{ secrets.DKRZ_GITLAB_TOKEN }}
        ref-type: tag
        ref-name: ${{ needs.levante-init.outputs.ref-name }}
        force: true
