name: GitLab CI
on:
  push:
    branches-ignore:
    - documentation
  pull_request:
    branches-ignore:
    - documentation

defaults:
  run:
    shell: bash

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - run: echo '${{ github.repository }}'
